name = "shorts-factory-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "shorts-factory-db"
database_id = "0e4eff77-347e-4474-88f0-cb0c86f01f2e"

[vars]
COLLECT_INTERVAL_HOURS = "2"
SHORTS_PER_COUNTRY = "100"
TARGET_COUNTRIES = "KR,US,UK,CA,AU,IN"
DAILY_QUOTA_LIMIT = "7200"

[triggers]
crons = ["0 */2 * * *"]